# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fdnodes_pb2 as fdnodes__pb2


class NodeExchangeStub(object):
    """
    service ModelAggregate {
    rpc get_aggr (super_model_aggregator) returns (stream model_aggregator) {};
    }

    service FileServer {
    rpc upload(stream Chunk) returns (Reply) {}
    rpc download(Request) returns (stream Chunk) {}
    }

    message Chunk {
    bytes buffer = 1;
    }

    message Request {
    string name = 1;
    }

    message Reply {
    int32 length = 1;
    }

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_args = channel.unary_unary(
                '/NodeExchange/get_args',
                request_serializer=fdnodes__pb2.fdnode.SerializeToString,
                response_deserializer=fdnodes__pb2.args_data.FromString,
                )


class NodeExchangeServicer(object):
    """
    service ModelAggregate {
    rpc get_aggr (super_model_aggregator) returns (stream model_aggregator) {};
    }

    service FileServer {
    rpc upload(stream Chunk) returns (Reply) {}
    rpc download(Request) returns (stream Chunk) {}
    }

    message Chunk {
    bytes buffer = 1;
    }

    message Request {
    string name = 1;
    }

    message Reply {
    int32 length = 1;
    }

    """

    def get_args(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeExchangeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_args': grpc.unary_unary_rpc_method_handler(
                    servicer.get_args,
                    request_deserializer=fdnodes__pb2.fdnode.FromString,
                    response_serializer=fdnodes__pb2.args_data.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NodeExchange', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NodeExchange(object):
    """
    service ModelAggregate {
    rpc get_aggr (super_model_aggregator) returns (stream model_aggregator) {};
    }

    service FileServer {
    rpc upload(stream Chunk) returns (Reply) {}
    rpc download(Request) returns (stream Chunk) {}
    }

    message Chunk {
    bytes buffer = 1;
    }

    message Request {
    string name = 1;
    }

    message Reply {
    int32 length = 1;
    }

    """

    @staticmethod
    def get_args(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NodeExchange/get_args',
            fdnodes__pb2.fdnode.SerializeToString,
            fdnodes__pb2.args_data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
