# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fdnodes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfdnodes.proto\"(\n\x06\x66\x64node\x12\x13\n\x06nodeid\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\t\n\x07_nodeid\"\x8d\x01\n\targs_data\x12\x17\n\nuser_index\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x14\n\x07\x64\x61taset\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x10\n\x03gpu\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x12\n\x05round\x18\x04 \x01(\x05H\x03\x88\x01\x01\x42\r\n\x0b_user_indexB\n\n\x08_datasetB\x06\n\x04_gpuB\x08\n\x06_round\"\x17\n\x05\x43hunk\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"\x17\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x17\n\x05Reply\x12\x0e\n\x06length\x18\x01 \x01(\x05\x32L\n\nFileServer\x12\x1c\n\x06upload\x12\x06.Chunk\x1a\x06.Reply\"\x00(\x01\x12 \n\x08\x64ownload\x12\x08.Request\x1a\x06.Chunk\"\x00\x30\x01\x32\x31\n\x0cNodeExchange\x12!\n\x08get_args\x12\x07.fdnode\x1a\n.args_data\"\x00\x62\x06proto3')



_FDNODE = DESCRIPTOR.message_types_by_name['fdnode']
_ARGS_DATA = DESCRIPTOR.message_types_by_name['args_data']
_CHUNK = DESCRIPTOR.message_types_by_name['Chunk']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_REPLY = DESCRIPTOR.message_types_by_name['Reply']
fdnode = _reflection.GeneratedProtocolMessageType('fdnode', (_message.Message,), {
  'DESCRIPTOR' : _FDNODE,
  '__module__' : 'fdnodes_pb2'
  # @@protoc_insertion_point(class_scope:fdnode)
  })
_sym_db.RegisterMessage(fdnode)

args_data = _reflection.GeneratedProtocolMessageType('args_data', (_message.Message,), {
  'DESCRIPTOR' : _ARGS_DATA,
  '__module__' : 'fdnodes_pb2'
  # @@protoc_insertion_point(class_scope:args_data)
  })
_sym_db.RegisterMessage(args_data)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), {
  'DESCRIPTOR' : _CHUNK,
  '__module__' : 'fdnodes_pb2'
  # @@protoc_insertion_point(class_scope:Chunk)
  })
_sym_db.RegisterMessage(Chunk)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'fdnodes_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'fdnodes_pb2'
  # @@protoc_insertion_point(class_scope:Reply)
  })
_sym_db.RegisterMessage(Reply)

_FILESERVER = DESCRIPTOR.services_by_name['FileServer']
_NODEEXCHANGE = DESCRIPTOR.services_by_name['NodeExchange']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FDNODE._serialized_start=17
  _FDNODE._serialized_end=57
  _ARGS_DATA._serialized_start=60
  _ARGS_DATA._serialized_end=201
  _CHUNK._serialized_start=203
  _CHUNK._serialized_end=226
  _REQUEST._serialized_start=228
  _REQUEST._serialized_end=251
  _REPLY._serialized_start=253
  _REPLY._serialized_end=276
  _FILESERVER._serialized_start=278
  _FILESERVER._serialized_end=354
  _NODEEXCHANGE._serialized_start=356
  _NODEEXCHANGE._serialized_end=405
# @@protoc_insertion_point(module_scope)
