# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedml.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66\x65\x64ml.proto\"c\n\x0c\x46\x65\x64mlRequest\x12\x12\n\nuser_index\x18\x01 \x01(\x05\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\x12\x0f\n\x07\x64\x61taset\x18\x03 \x01(\t\x12\x0b\n\x03gpu\x18\x04 \x01(\x05\x12\r\n\x05round\x18\x05 \x01(\x05\"!\n\x12ManagementResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2K\n\x16\x46\x65\x64MlManagementService\x12\x31\n\tUserIndex\x12\r.FedmlRequest\x1a\x13.ManagementResponse\"\x00\x62\x06proto3')



_FEDMLREQUEST = DESCRIPTOR.message_types_by_name['FedmlRequest']
_MANAGEMENTRESPONSE = DESCRIPTOR.message_types_by_name['ManagementResponse']
FedmlRequest = _reflection.GeneratedProtocolMessageType('FedmlRequest', (_message.Message,), {
  'DESCRIPTOR' : _FEDMLREQUEST,
  '__module__' : 'fedml_pb2'
  # @@protoc_insertion_point(class_scope:FedmlRequest)
  })
_sym_db.RegisterMessage(FedmlRequest)

ManagementResponse = _reflection.GeneratedProtocolMessageType('ManagementResponse', (_message.Message,), {
  'DESCRIPTOR' : _MANAGEMENTRESPONSE,
  '__module__' : 'fedml_pb2'
  # @@protoc_insertion_point(class_scope:ManagementResponse)
  })
_sym_db.RegisterMessage(ManagementResponse)

_FEDMLMANAGEMENTSERVICE = DESCRIPTOR.services_by_name['FedMlManagementService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FEDMLREQUEST._serialized_start=15
  _FEDMLREQUEST._serialized_end=114
  _MANAGEMENTRESPONSE._serialized_start=116
  _MANAGEMENTRESPONSE._serialized_end=149
  _FEDMLMANAGEMENTSERVICE._serialized_start=151
  _FEDMLMANAGEMENTSERVICE._serialized_end=226
# @@protoc_insertion_point(module_scope)
