# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpcfedml_pb2 as grpcfedml__pb2


class GrpcfedMLServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.grpcArgsParser = channel.unary_unary(
                '/GrpcfedMLService/grpcArgsParser',
                request_serializer=grpcfedml__pb2.FedmlRequest.SerializeToString,
                response_deserializer=grpcfedml__pb2.ManagementResponse.FromString,
                )


class GrpcfedMLServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def grpcArgsParser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcfedMLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'grpcArgsParser': grpc.unary_unary_rpc_method_handler(
                    servicer.grpcArgsParser,
                    request_deserializer=grpcfedml__pb2.FedmlRequest.FromString,
                    response_serializer=grpcfedml__pb2.ManagementResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GrpcfedMLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GrpcfedMLService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def grpcArgsParser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GrpcfedMLService/grpcArgsParser',
            grpcfedml__pb2.FedmlRequest.SerializeToString,
            grpcfedml__pb2.ManagementResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
