# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcfedml.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgrpcfedml.proto\"O\n\x0c\x46\x65\x64mlRequest\x12\x12\n\nuser_index\x18\x01 \x01(\x05\x12\x0f\n\x07\x64\x61taset\x18\x02 \x01(\t\x12\x0b\n\x03gpu\x18\x03 \x01(\x05\x12\r\n\x05round\x18\x04 \x01(\x05\"U\n\x12ManagementResponse\x12\x12\n\nuser_index\x18\x01 \x01(\x05\x12\x0f\n\x07\x64\x61taset\x18\x02 \x01(\t\x12\x0b\n\x03gpu\x18\x03 \x01(\x05\x12\r\n\x05round\x18\x04 \x01(\x05\x32H\n\x10GrpcfedMLService\x12\x34\n\x0egrpcArgsParser\x12\r.FedmlRequest\x1a\x13.ManagementResponseb\x06proto3')



_FEDMLREQUEST = DESCRIPTOR.message_types_by_name['FedmlRequest']
_MANAGEMENTRESPONSE = DESCRIPTOR.message_types_by_name['ManagementResponse']
FedmlRequest = _reflection.GeneratedProtocolMessageType('FedmlRequest', (_message.Message,), {
  'DESCRIPTOR' : _FEDMLREQUEST,
  '__module__' : 'grpcfedml_pb2'
  # @@protoc_insertion_point(class_scope:FedmlRequest)
  })
_sym_db.RegisterMessage(FedmlRequest)

ManagementResponse = _reflection.GeneratedProtocolMessageType('ManagementResponse', (_message.Message,), {
  'DESCRIPTOR' : _MANAGEMENTRESPONSE,
  '__module__' : 'grpcfedml_pb2'
  # @@protoc_insertion_point(class_scope:ManagementResponse)
  })
_sym_db.RegisterMessage(ManagementResponse)

_GRPCFEDMLSERVICE = DESCRIPTOR.services_by_name['GrpcfedMLService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FEDMLREQUEST._serialized_start=19
  _FEDMLREQUEST._serialized_end=98
  _MANAGEMENTRESPONSE._serialized_start=100
  _MANAGEMENTRESPONSE._serialized_end=185
  _GRPCFEDMLSERVICE._serialized_start=187
  _GRPCFEDMLSERVICE._serialized_end=259
# @@protoc_insertion_point(module_scope)
