version: "3.3"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345root
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "0.0.0.0:5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: jahanxbkhan@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345root
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
